.ifndef PPU_INC
PPU_INC = 1
; -----------------------------------------------------------------------------
;   File: PPU.inc
;   Description: Holds address symbols for all subroutines defined in PPU.s
; -----------------------------------------------------------------------------

;----- Import ------------------------------------------------------------------
.import     LoadVRAM
.import     LoadCGRAM
.import     UpdateOAMRAM
;-------------------------------------------------------------------------------
.endif
